name: "jenkins"
version: 2.73.1-1
gitUrl: "https://api.github.com/repos/devopskube/docker-jenkins/tags"
imageName: "devopskube/jenkins"
issueProjectName: "foo"
codeReview: true
chatRoom: "devopskube"
